// src/pages/robots.txt.ts
import type { APIRoute } from 'astro';
import { SITE } from '../constants/site';

export const GET: APIRoute = () => {
  const robotsTxt = `
User-agent: *
Allow: /
Disallow: /api/
Disallow: /funnel/
Disallow: /ads/

# Auto-generated by @astrojs/sitemap integration
Sitemap: ${SITE.url}/sitemap-index.xml
`.trim();

  return new Response(robotsTxt, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      // Edge Caching: Cloudflare caches this globally for 24 hours
      'Cache-Control': 'public, max-age=86400, s-maxage=86400, stale-while-revalidate=86400'
    },
  });
};