// src/pages/robots.txt.ts
import type { APIRoute } from 'astro';
import { SITE } from '../constants/site';

export const prerender = true;

export const GET: APIRoute = () => {
  const robotsTxt = `
User-agent: *
Allow: /
Allow: /getting-started/signup
Disallow: /getting-started/complete
Disallow: /getting-started/success
Disallow: /api/

# AI search engines — allowed to index public marketing & course content, but blocked from internal API & private session routes
User-agent: GPTBot
Allow: /
Allow: /getting-started/signup
Disallow: /getting-started/complete
Disallow: /getting-started/success
Disallow: /api/

User-agent: ClaudeBot
Allow: /
Allow: /getting-started/signup
Disallow: /getting-started/complete
Disallow: /getting-started/success
Disallow: /api/

User-agent: PerplexityBot
Allow: /
Allow: /getting-started/signup
Disallow: /getting-started/complete
Disallow: /getting-started/success
Disallow: /api/

User-agent: Applebot-Extended
Allow: /
Allow: /getting-started/signup
Disallow: /getting-started/complete
Disallow: /getting-started/success
Disallow: /api/

# Auto-generated by @astrojs/sitemap integration
Sitemap: ${SITE.url}/sitemap-index.xml
`.trim();

  return new Response(robotsTxt, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      // Edge Caching: Cloudflare caches this globally for 24 hours
      'Cache-Control': 'public, max-age=86400, s-maxage=86400, stale-while-revalidate=86400',
    },
  });
};
